# Application
debug: true
server:
  port: 8000

# Database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/automobile_company
    username: konex
    password: konex
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR